### ISSUE TITLE
Nog steeds probleem met dat grote logo

### ISSUE THREAD

**Issue by Theo-denBlanken** [FirasSoekhai/sasstraining#1]
heb je het een update gegeven? 
Neem anders weer contact met mij op.

**Comment by FirasSoekhai** [comment]
logo kleiner gemaakt en checkbox in het logo samengevoegd

**Comment by Theo-denBlanken** [comment]
Dag Firas,

Bekijk deze screenshot goed en ga na welke actie je had kunnen ondernemen….


[Afbeelding met schermafbeelding  Automatisch gegenereerde beschrijving]

Met vriendelijke groeten,

--

[ma-logo]
Theo den Blanken

[Theo]<http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam
[Twitter]<https://twitter.com/theodenblanken/> [WordPress] <http://bla.hosts.ma-cloud.nl/>
